Чернышёв Александр
urfu-2017/javascript-task-3 pull request #2
Opened 2017-10-13 06:00 UTC by aleksch

2017-10-13 06:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-13 06:00 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-10-13 07:43 UTC, eugenest commented
чекну на выходных

2017-10-13 12:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-13 12:20 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-10-15 15:58 UTC, eugenest commented
Общая претензия: непрозрачный флоу выполнения / данных. Обозначу меткой **[1]**, дальше по коду детальнее покажу.

2017-10-15 18:01 UTC, eugenest requested changes
Причухивай, будут вопросы — я в телеге @tim_evg

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +    var answerArray = getAnswerArray();
**[1]**

Метод getAppropriateMoment принимает 3 аргумента, но методы getAnswerArray(), getArrOfGoodTime(),  getBusyIntervals() не принимают их явно, а получают от родительского скоупа. Стоило бы сделать эти методы более [чистыми](https://habrahabr.ru/post/154105/) (какие-то данные передал в метод, обработал, вернул) и вынести отдельно от getAppropriateMoment.

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +    var answer = answerArray.length === 0 ? -1 : answerArray[0][0];
достаточно просто `!answerArray.length`
а точно в answerArray[0] есть [0]?

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +    function getArrOfGoodTime() {
не стоит использовать в названии функции тип возвращаемого значения, лучше использовать jsdoc.

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +
лишние пустые строки

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        var resultArray = [];
блок объявления переменных лучше отделить от остального кода пустыми строками

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +
дырки в блоке объявления переменных не нужны

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        return Number(stringTime.substring(stringTime.length - 1));
а Магадан? (+11)

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +            if ({}.hasOwnProperty.call(schedule, friend)) {
schedule.hasOwnProperty(friend) ?

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +
пустая строка

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +    function getTimestamp(stringTime) {
злоупотребляешь сабстрингом
регулярка здесь выглядела бы уместнее

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        var minuts = Number(stringTime.substring(6, 8));
minutes

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        var sortAndMergeArray = mergeRange(busyIntervals);
называние переменной не понятное, плюс название метода говорит только о том, что вернётся что-то смёрженное. Короче, сортировку бы вынес отдельно. Имя переменной не должно содержать информации о типе хранимого значения.

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        for (var i = 1; i < sortAndMergeArray.length; i++) {
Array.map смотрелся бы здесь лучше

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +            timeArray.push(
неконсистентное выравнивание 92-95

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        for (var i = 1; i < sortedArray.length; i++) {
Array.forEach лаконичнее

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +                ans += 30;
30 можно вынести в константу

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        for (var i = 0; i < scheduleArray.length; i++) {
.map

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        if (stringTime.substring(0, 2) === 'ВТ') {
если уж сабстринги, то stringTime.substring(0, 2) можно вынести вверх, в этом методе он используется трижды

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +            return answer >= 0;
к проблеме **[1]**: в этом месте кода уже не понятно, что это за answer такой

2017-10-15 18:01 UTC, eugenest commented on robbery.js
> +        arrIntervals.push([0, bankStartWork], [bankFinishWork, bankStartWork + MIN_PER_DAY],
неуниверсально

2017-10-17 07:04 UTC, eugenest commented
🍅

2017-10-17 07:26 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-17 07:26 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-10-18 15:36 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-18 15:36 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-10-19 06:36 UTC, eugenest approved these changes

2017-10-19 06:37 UTC, eugenest commented
🍏

2017-10-19 06:40 UTC, closed without merging