Стихин Семен
urfu-2017/javascript-task-3 pull request #21
Opened 2017-10-15 20:16 UTC by samstikhin

2017-10-15 20:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 05:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-16 07:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-16 07:12 UTC, honest-hrundel commented
@maxvipon обрати внимание: решено доп. задание

2017-10-19 07:04 UTC, maxvipon commented on robbery.js
> +    var DaysToNum = { 'ПН': 0, 'ВТ': 1, 'СР': 2 };
а остальные дни?

2017-10-19 07:10 UTC, maxvipon commented on robbery.js
> +            var parseDate = timeString.split(/ |:|\+/);
_На будущее_: если использовать такой подход, то `timeString` нужно сперва валидировать, иначе получишь ерунду в `parseData`.

2017-10-19 07:22 UTC, maxvipon requested changes
Нужно сделать решение, которое будет работать на любом наборе входных данных, а не только на примере.

2017-10-19 07:22 UTC, maxvipon commented on robbery.js
> +    var MinInHour = 60;
такое лучше писать `const MIN_IN_HOUR = 60`, чтобы сразу видеть константы в коде

2017-10-19 07:22 UTC, maxvipon commented on robbery.js
> +            aa = aa.replace('%HH', hour);
Можно объединять
```js
return template.replace('%DD', day).replace('%HH', hour)
```

2017-10-19 07:22 UTC, maxvipon commented on robbery.js
> +            var guyInterval = exports.converter().toNumberInterval(schedule[guy][i]);
здесь и ниже `exports.converter()` используешь повторно раз, нужно вынести в переменную

2017-10-19 07:22 UTC, maxvipon commented on robbery.js
> +    var curInterval = exports.converter().toNumberInterval(timeInterval);
`var currentInterval`
Лучше писать полностью, не нужно лениться

2017-10-19 07:22 UTC, maxvipon commented on robbery.js
> +    var answer = true;
Это не корректно – для пустого `schedule` вернешь `true`

2017-10-19 07:22 UTC, maxvipon commented on robbery.js
> +    var bankWorkingIntervals = [
❌ Хардкод! Сразу же сломается на других входных данных. Нужно универсально решение.

2017-10-20 13:19 UTC, samstikhin commented on robbery.js
> +    var answer = true;
Так это корректно: если расписание пустое, значит все свободны и им подойдет любой момент.

2017-10-20 15:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-20 15:46 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-20 15:46 UTC, honest-hrundel commented
@maxvipon обрати внимание: решено доп. задание

2017-10-20 18:22 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-20 18:22 UTC, honest-hrundel commented
@maxvipon обрати внимание: решено доп. задание

2017-10-23 13:24 UTC, maxvipon approved these changes
🆗

2017-10-23 13:27 UTC, maxvipon commented
Хорошо порефакторил, молодец!

2017-10-23 13:27 UTC, closed without merging