Захаров Алексей
urfu-2017/javascript-task-3 pull request #28
Opened 2017-10-16 18:45 UTC by Az404

2017-10-16 18:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-17 08:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-17 11:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-17 12:00 UTC, honest-hrundel commented
@gogoleff обрати внимание: решено доп. задание

2017-11-27 08:18 UTC, dotokoto requested changes

2017-11-27 08:18 UTC, dotokoto commented on robbery.js
> +        DAY_NAMES.slice(0, 3).map(day => appendDay(day, workingHours)));
Лучше держать число 3 в виде константы

2017-11-27 08:18 UTC, dotokoto commented on robbery.js
> +                result = findPeriod(currentTime + 30, periodsToFind, excludePeriods, duration);
30 - тоже константа

2017-11-27 08:18 UTC, dotokoto commented on robbery.js
> +            return result !== null;
Можно переписать эту функцию проще:

```(javascript)
if (!currentTime) {
    return false;
}

let result = findPeriod(...);
if (result) { 
    currentTime = result;
}

return Boolean(result);
```

2017-11-27 08:18 UTC, dotokoto commented on robbery.js
> +        day = undefined;
`undefined` - это неопределенное значение, его не принято присваивать напрямую. В таких случаях правильнее использовать `null`

2017-11-27 08:18 UTC, dotokoto commented on robbery.js
> +    return createTimeParts(day, Number(hours), Number(minutes), Number(timezone));
Если в day попадет `undefined`, разве функция `getAbsoluteValue ` будет работать нормально? 
В условиях задачи было сказано, что даты всегда приходят правильно. Так что день всегда должен быть

2017-11-27 08:18 UTC, Dotokoto commented on robbery.js
> +    let dayPart = absoluteTime % MINUTES_PER_DAY;
Почему везде `const`, а тут `let`?

2017-11-29 06:11 UTC, Az404 commented on robbery.js
> +    return createTimeParts(day, Number(hours), Number(minutes), Number(timezone));
В аргументе workingHours нет дня, а эта функция используется для определения таймзоны:
```let baseTimezone = parseTimeParts(workingHours.from).timezone;```

2017-11-29 06:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-11-29 06:16 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2017-11-29 10:02 UTC, dotokoto approved these changes

2017-11-29 10:02 UTC, Dotokoto commented
Принято с полным баллом

2017-11-29 10:02 UTC, closed without merging