Ильенко Кристина
urfu-2017/javascript-task-3 pull request #35
Opened 2017-10-17 15:22 UTC by chrighter

2017-10-17 15:22 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-17 15:22 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-18 15:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-18 15:09 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-22 15:27 UTC, Mokoshka requested changes

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    let bankTimezone = parseDate(workingHours.from).timezone;
У нас есть небольшое правило для использования const и let: если переменная не изменяется внутри функции, то мы используем const, если переменной необходимо изменить значение, то используем let. Удобное правило, можешь воспользоваться им, если захочешь

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    sheduleWithBank.bank = notWorkingHoursOfBank;
Можно сделать так:
```
let sheduleWithBank = Object.assign({ bank: notWorkingHoursOfBank }, schedule);
```

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +        item.forEach(elem => {
Названия переменных item и elem непонятны. Хочется, чтобы название переменной говорило о том, что в ней содержится

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    translatedTime = hours * 60 + minutes + DAYS.indexOf(day) * 24 * 60;
А почему сразу не присвоить значение переменной?

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    if (bankTimezone !== robberTimezone) {
А нужен ли if? Если таймзоны будут совпадать, то разница будет 0

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    let LeftBorderOfInterval = [];
Почему с большой буквы?

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    sortedSchedule.forEach(item => {
item снова плохое название для переменной

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +        if (countFrom === 0) {
Так как 0 кастуется к false, то if можно переписать `if (!countFrom)`

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +            lengthOfInterval.push(currentStartMinutes - previousEndMinutes);
Я бы назвала массивы с намеком на то, что там несколько элементов. Например, leftBordersOfInterval и lengthsOfInterval

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    }
Я бы сделала другой формат данных в interval. Я бы сделала его массивом объектов, в котором есть начало интервала и продолжительность, а потом с помощью find нашла бы тот, который удовлетворяет условию задачи

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +            return timeForRobbery !== undefined;
`return Boolean(timeForRobbery)`?

2017-10-22 15:27 UTC, Mokoshka commented on robbery.js
> +    if (day === undefined) {
`if (!day)`?

2017-10-24 09:55 UTC, chrighter commented on robbery.js
> +            return timeForRobbery !== undefined;
А если время начала ограбления будет 00:00 ПН? То есть мне придёт 0 минут, в результате  я получу false, но это же будет неверно для данного случая

2017-10-24 09:56 UTC, Mokoshka commented on robbery.js
> +            return timeForRobbery !== undefined;
Тогда ок

2017-10-24 10:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-24 10:00 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-24 10:00 UTC, chrighter commented on robbery.js
> +            return timeForRobbery !== undefined;
Остальное поправила

2017-10-24 10:36 UTC, Mokoshka requested changes
Давай сделаем метод tryLater проще

2017-10-24 10:36 UTC, Mokoshka commented on robbery.js
> +    let timeForRobbery = (appropriateInterval) ? appropriateInterval.leftBorder : undefined;
Скобочки лишние

2017-10-24 10:36 UTC, Mokoshka commented on robbery.js
> +    return String(number);
return `0{number}`.slice(-2);

2017-10-24 10:36 UTC, Mokoshka commented on robbery.js
> +    const appropriateInterval = intervals.find(interval => interval.size >= duration);
Здесь можно отфильтровать получившийся результат. Тогда тебе надо будет брать первый элемент из этого массива.
Тогда функция tryLater должна стать проще.

2017-10-24 15:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-24 15:44 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-24 15:48 UTC, chrighter commented on robbery.js
> +    const appropriateInterval = intervals.find(interval => interval.size >= duration);
Замечания исправила: теперь использую filter, беру нулевой элемент

2017-10-25 21:30 UTC, Mokoshka requested changes
Последние правки и приму задачу

2017-10-25 21:30 UTC, Mokoshka commented on robbery.js
> +            parsedSchedule.push({ minutes: timeToInMinutes, step: 'to' });
Можно делать `parsedSchedule.push({...}, {...})`

2017-10-25 21:30 UTC, Mokoshka commented on robbery.js
> +    DAYS.forEach(day => {
Здесь будет логичнее использовать reduce(). И один вызов метод push с двумя арргументами

2017-10-25 21:30 UTC, Mokoshka commented on robbery.js
> +    sortedSchedule.forEach(event => {
Здесь тоже reduce больше подойдет. Всегда, когда проходишь циклом и у тебя есть объект-аккумулятор, используй reduce

2017-10-26 06:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-26 06:58 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-26 06:59 UTC, chrighter commented on robbery.js
> +    sortedSchedule.forEach(event => {
исправила

2017-10-26 08:24 UTC, Mokoshka approved these changes

2017-10-26 08:24 UTC, closed without merging