Base test passed
urfu-2017/javascript-task-3 pull request #38
Opened 2017-10-17 16:13 UTC by KIlyaA

2017-10-17 16:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2017-10-17 17:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2017-10-17 17:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 19

2017-10-17 18:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2017-10-17 20:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 16

2017-10-17 20:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2017-10-17 20:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2017-10-17 20:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2017-10-17 20:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 6 из 16

2017-10-17 20:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 16

2017-10-18 07:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2017-10-18 07:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2017-10-18 08:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-18 08:05 UTC, honest-hrundel commented
@sameoldmadness обрати внимание: решено доп. задание

2017-10-18 08:36 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-18 08:36 UTC, honest-hrundel commented
@sameoldmadness обрати внимание: решено доп. задание

2017-10-19 19:40 UTC, sameoldmadness requested changes

2017-10-19 19:40 UTC, sameoldmadness commented on timeline.js
> +    return Date.parse(`${DAYS[day]} Jan 2017 ${hours}:${minutes}:00 GMT+${timezone}`);
Почему не `Date.UTC`?

2017-10-19 19:40 UTC, sameoldmadness commented on timeline.js
> +const TIME_FORMAT = /^([А-Я]{2})\s([01]?[0-9]|2[0-3]):([0-5][0-9]|[0-9])\+(\d+)$/;
`([А-Я]{2})` -> `(ПН|ВТ|СР)`

2017-10-19 19:40 UTC, sameoldmadness commented on timeline.js
> +const TIME_FORMAT = /^([А-Я]{2})\s([01]?[0-9]|2[0-3]):([0-5][0-9]|[0-9])\+(\d+)$/;
`([0-5][0-9]|[0-9])` -> `([0-5]?[0-9])`

2017-10-19 19:40 UTC, sameoldmadness commented on timeline.js
> +const TIME_FORMAT = /^([А-Я]{2})\s([01]?[0-9]|2[0-3]):([0-5][0-9]|[0-9])\+(\d+)$/;
`\d` -> `[0-9]`, для единообразия

2017-10-19 19:40 UTC, sameoldmadness commented on timeline.js
> +const DAYS = { 'ПН': '01', 'ВТ': '02', 'СР': '03', 'ЧТ': '04', 'ПТ': '05', 'СБ': '06', 'ВС': '07' };
Кавычки для ключей не нужны.

А массив тут не подойдёт?

2017-10-19 19:40 UTC, sameoldmadness commented on timeline.js
> +exports.Timeline = Timeline;
Обычно основной объект экспортируют в качестве дефолтного, а остальное кладут ему в свойства.

2017-10-19 19:44 UTC, KIlyaA commented on timeline.js
> +const DAYS = { 'ПН': '01', 'ВТ': '02', 'СР': '03', 'ЧТ': '04', 'ПТ': '05', 'СБ': '06', 'ВС': '07' };
Массив подойдёт, но с объектом доступ вроде как доступ быстрее, да и нагляднее
Кавычки из-за того кириллица)

2017-10-19 19:48 UTC, KIlyaA commented on timeline.js
> +    return Date.parse(`${DAYS[day]} Jan 2017 ${hours}:${minutes}:00 GMT+${timezone}`);
Были проблемы с правильным конвертированием временной зоны.
Поэтому решил выбрать более наглядный подход, но знаю, что не стандартизировано, но на ноде работать будет

2017-10-19 20:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-19 20:12 UTC, honest-hrundel commented
@sameoldmadness обрати внимание: решено доп. задание

2017-10-19 20:14 UTC, sameoldmadness commented on timeline.js
> +exports.default = Timeline;
Не-не-не : )

```js
module.exports = Timeline;
```

И `default` на принимающей стороне становится не нужен.

2017-10-19 20:15 UTC, sameoldmadness commented on timeline.js
> +const DAYS = { 'ПН': '01', 'ВТ': '02', 'СР': '03', 'ЧТ': '04', 'ПТ': '05', 'СБ': '06', 'ВС': '07' };
Ну а зачем кавычки для кириллицы?

2017-10-19 20:16 UTC, sameoldmadness commented on timeline.js
> +    return Date.parse(`${DAYS[day]} Jan 2017 ${hours}:${minutes}:00 GMT+${timezone}`);
Я бы тогда предложил формат ISOString парсить, он хотя бы стандартизован.

2017-10-19 20:18 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-19 20:18 UTC, honest-hrundel commented
@sameoldmadness обрати внимание: решено доп. задание

2017-10-19 20:18 UTC, sameoldmadness approved these changes

2017-10-19 20:18 UTC, sameoldmadness commented
:shipit:

2017-10-19 20:18 UTC, closed without merging