First attempt
urfu-2017/javascript-task-3 pull request #40
Opened 2017-10-18 07:50 UTC by Lyapa96

2017-10-18 07:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 07:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 16

2017-10-18 13:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 14:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2017-10-18 14:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 19

2017-10-18 14:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 14:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 18:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 19:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 20:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-18 21:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-19 07:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-19 07:20 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-10-23 08:21 UTC, savichev-igor requested changes
Очень хорошее решение 🔥 

Незначительные правки и улучшения

🍅

2017-10-23 08:21 UTC, savichev-igor commented on .vscode/launch.json
> +{
Кажется, что это не надо было пушить

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +const INTERVALS_END = HOURS_IN_DAY * 3 * 60 - 1;
А почему `-1` делаешь, а не 0.00001, например?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.spec.js
> +describe('robbery.getAppropriateMoment()', function () {
Расширил для себя тест-кейсы)?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
>          format: function (template) {
Весьма элегантно)

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +    for (var i = 0; i < workDays.length; i++) {
`forEach`?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +    let allMinutes = (hours + timeZoneDifferent + daysOfWeeksToNumberDay[day] * HOURS_IN_DAY) *
Мог сразу вернуть это значение, по идее. Раз эта переменная нигде больше не используется внутри функции

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +    let sortedEmploymentIntervals = employmentIntervals.sort((a, b) => a.start - b.start);
🔥

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +    for (var i = 0; i < sortedIntervals.length; i++) {
Что-нибудь из перебирающих методов не пробовал тут?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +    let result = [];
Перенос?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +            let nextAnswer = getNextAnswer(currentAnswer, appropriateMoments, duration);
Перенос?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +var numberDayToDayWeek = {
Не пробовал никак заиспользовать предыдущий объект, чтобы не дублировать?

2017-10-23 08:21 UTC, savichev-igor commented on robbery.js
> +            start: getTimeInMinutes(day, BANK_TIMEZONE_DIFF, from.hours, from.minutes),
Не совсем понимаю смысла этой константы с нулём, если она нигде больше не используется

2017-10-23 08:21 UTC, Savichev-Igor commented on robbery.js
> +
В принципе можно было бы добавить где-нибудь на ранних этапах проверку, которая бы отсекала все интервалы, которые короче времени работы банка, чтобы потом было меньше объектов для перебора и поиска

2017-10-23 08:21 UTC, Savichev-Igor commented on robbery.js
> +    let intervals = unionEmploymentIntervals.filter(x => x.start < INTERVALS_END)
Круто, что отсекаешь ненужное

2017-10-23 08:22 UTC, Savichev-Igor commented on robbery.js
> +    for (var i = 0; i < sortedIntervals.length; i++) {
И ещё бы перенос добавил перед `for`

2017-10-24 05:49 UTC, Lyapa96 commented on .vscode/launch.json
> +{
Да, согласен, постараюсь не добавлять, просто  на автомате пишу git add .

2017-10-24 05:53 UTC, Lyapa96 commented on robbery.js
> +var numberDayToDayWeek = {
Я думал об этом, но я не нашел это в первой ссылке гугла, решил, что это можно сделать только костыльно и проще будет просто завести еще один объект, будет круто, если скинешь какой нибудь пример, как это можно сделать

2017-10-24 05:55 UTC, Lyapa96 commented on robbery.js
> +const INTERVALS_END = HOURS_IN_DAY * 3 * 60 - 1;
Понял, сделаю так в других задачах) 
Оправдание - в этой банк ограничен в работе до 23:59 среды, поэтому -1

2017-10-24 05:58 UTC, Lyapa96 commented on robbery.js
> +    for (var i = 0; i < workDays.length; i++) {
Done.

2017-10-24 06:03 UTC, Lyapa96 commented on robbery.js
> +            start: getTimeInMinutes(day, BANK_TIMEZONE_DIFF, from.hours, from.minutes),
Done. Перенес константу в функцию

2017-10-24 06:05 UTC, Lyapa96 commented on robbery.js
> +    let allMinutes = (hours + timeZoneDifferent + daysOfWeeksToNumberDay[day] * HOURS_IN_DAY) *
Done. Наверно дебажил и забыл убрать.

2017-10-24 06:09 UTC, Lyapa96 commented on robbery.js
> +    for (var i = 0; i < sortedIntervals.length; i++) {
Перенос - done. Перебирающие это (foreach, for (lert obj of objs)?

2017-10-24 06:11 UTC, Lyapa96 commented on robbery.js
> +    let result = [];
Done.

2017-10-24 06:21 UTC, Lyapa96 commented on robbery.spec.js
> +describe('robbery.getAppropriateMoment()', function () {
Я написал первое решение, и у меня не проходило 4 теста, написал этот тот кейс нашел ошибку, исправил, но по прежднему не проходило 4 теста, потом просто все удалил написал с самого начала, тесты прошли с первого раза, я подозреваю, что проблемы были в поганой функцией map, которая изменяет исходную коллекцию, даже если делаешь var newItems = items.slice(); newItems.map(x=>...) , кароче я не рассчитывал на такую подставу со стороны этой функции

2017-10-24 06:22 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-24 06:22 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-10-24 06:38 UTC, Savichev-Igor commented on .vscode/launch.json
> +{
В будущем добавлять такие файлы можно в `.gitignore`, а если они уже попали в индекс, то написать

`git rm --cached -r .vscode` - это удалит их из индекса, но локально они у тебя останутся. Ты сделаешь коммит и в индекс они уже попадать не будут

2017-10-24 06:42 UTC, Savichev-Igor commented on robbery.js
> +var numberDayToDayWeek = {
```
function getKeyByValue(object, value) {
    return Object.keys(object).find(key => object[key] === value);
}
```

ES6 солюшин

2017-10-24 06:46 UTC, Savichev-Igor commented on robbery.js
> +    let workDays = ['ПН', 'ВТ', 'СР'];
Наверное, тоже можно было в константы вынести

2017-10-24 06:50 UTC, Savichev-Igor commented on robbery.js
> +    for (var i = 0; i < sortedIntervals.length; i++) {
Тот же `forEach` мог заиспользовать

2017-10-24 06:50 UTC, Savichev-Igor commented on robbery.js
> +            let nextAnswer = getNextAnswer(currentAnswer, appropriateMoments, duration);
Перед `if` лично я бы всегда ставил перенос строки, отделяя конструкции

2017-10-24 06:51 UTC, savichev-igor approved these changes
⭐️

2017-10-24 06:52 UTC, closed without merging