не факт что правильно
urfu-2017/javascript-task-3 pull request #42
Opened 2017-10-18 09:52 UTC by HazipovVF

2017-10-18 09:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 09:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 16

2017-10-18 11:08 UTC, HazipovVF commented
🔔

2017-10-18 11:10 UTC, HazipovVF commented
Никак не могу понять, где ошибка
если я запускаю 1 тест, то все верно

var moment = robbery.getAppropriateMoment(gangSchedule, 90, bankWorkingHours);
console.info(moment.exists());
console.info(moment.format('Метим на %DD, старт в %HH:%MM!'));

2017-10-18 11:11 UTC, HazipovVF commented
если же 2, то результат 2го не верен
var longMoment = robbery.getAppropriateMoment(gangSchedule, 121, bankWorkingHours);

// Выведется false и ""
console.info(longMoment.exists());
console.info(longMoment.format('Метим на %DD, старт в %HH:%MM!'));

// Время существует
var moment = robbery.getAppropriateMoment(gangSchedule, 90, bankWorkingHours);
// Выведется true и "Метим на ВТ, старт в 11:30!"
console.info(moment.exists());
console.info(moment.format('Метим на %DD, старт в %HH:%MM!'));

2017-10-18 14:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 16

2017-10-18 15:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 16

2017-10-18 21:49 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-18 22:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 23:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-18 23:10 UTC, honest-hrundel commented
@evilj0e обрати внимание: решено доп. задание

2017-10-24 07:44 UTC, evilj0e requested changes
🍅

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +const DAY = 2;
Что за константы, которые определяют день/месяц/год? Для чего они?

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    var gangShe = getGangShedule(schedule, timeZone);
gang she 😂

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    var gangShe = getGangShedule(schedule, timeZone);
schedule

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    var timeToRob = itsTime(noRob, duration);
И тут тоже

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    var noRob = getBusyTime(noRobbery(timeNotToRob, bankNotWorkingHours));
Переименуй название функции. По ней непонятно, что вообще она делает.

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +            if (timeToRob[0] !== undefined) {
`return timeToRob[0] !== undefined;` ?

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +            var hour = '0' + timeToRob[0].from.getHours();
у тебя же определена функция `beautify`

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +            if (timeToRob[0].to - timeToRob[0].from >= (duration + 30) * 60 * 1000) {
30, 60, 1000 вынеси в константы и назови более осмысленно

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +                new Date (timeToRob[0].from.setMinutes(timeToRob[0].from.getMinutes() + 30));
Тут забыл таб

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    for (var i = 0; i < 3; i++) {
Здесь ты завязан на количество участников, а это плохо. Тебе стоит где-то хранить нападающих и везде использовать это знание

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +
Лишний перенос

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +
Лишнее

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    var hour = date.slice(3, 5);
По коду много слайсов. Ты мог один раз распарсить их и везде использовать готовые данные.

2017-10-24 07:44 UTC, evilj0e commented on robbery.js
> +    return timeNotToRob.sort(function (a, b) {
Такой метод сортировки у тебя уже был реализован выше. Переиспользуй

2017-10-24 11:34 UTC, HazipovVF commented on robbery.js
> +            var hour = '0' + timeToRob[0].from.getHours();
писал в разное время 
уже забыл что она была

2017-10-24 11:35 UTC, HazipovVF commented on robbery.js
> +const DAY = 2;
У меня все в формате Date, а для него нужны какие-то день, месяц, год
Выбрал эту дату как изначальную

2017-10-24 11:35 UTC, HazipovVF commented on robbery.js
> +    var gangShe = getGangShedule(schedule, timeZone);
попортил когда исправлял

2017-10-24 11:37 UTC, evilj0e commented on robbery.js
> +const DAY = 2;
Не понял твой комментарий

2017-10-24 11:39 UTC, HazipovVF commented
В ближайшее время исправлю

2017-10-24 12:44 UTC, HazipovVF commented on robbery.js
> +const DAY = 2;
пример
return new Date(YEAR, MONTH, DAY + i, hour, minutes);
перевод времени работы банка в date

2017-10-24 14:00 UTC, HazipovVF commented on robbery.js
> +    var hour = date.slice(3, 5);
Так и старался 
Два слайса во времени работы банка
3 слайса во времени ограбления
остальные слайсы у меня в цикле в normalizeTimezone

2017-10-24 14:04 UTC, HazipovVF commented on robbery.js
> +const DAY = 2;
return new Date(YEAR, MONTH, DAY + deltaDay, hour, minutes);
я не могу создать дату без заданного года месяца и дня

2017-10-24 14:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2017-10-24 14:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2017-10-24 16:41 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-24 16:41 UTC, honest-hrundel commented
@evilj0e обрати внимание: решено доп. задание

2017-10-24 16:46 UTC, HazipovVF commented on robbery.js
> +
Данная функция должна сдвигать ровно на день
Например было ПН 23:00 +3, если временная зона банка +5
Должно стать ВТ 01:00 +5
Если break убрать то будет ВС

2017-10-24 16:47 UTC, HazipovVF commented on robbery.js
> +
сейчас дошло 
можно от этого избавится, но понадобится новая переменная

2017-10-27 05:50 UTC, evilj0e approved these changes

2017-10-27 05:50 UTC, evilj0e commented
⭐️

2017-10-27 05:50 UTC, closed without merging

2017-10-27 05:52 UTC, evilj0e commented
Поправил теги, потому что не успел проверить. Студент сделал вовремя.