Рогов Александр
urfu-2017/javascript-task-3 pull request #44
Opened 2017-10-18 12:05 UTC by San4eyZ

2017-10-18 12:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 15:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2017-10-19 03:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2017-10-19 03:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-19 04:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 16

2017-10-19 04:15 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-19 04:15 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-24 09:08 UTC, Mokoshka requested changes
Давай упростим работу с датой, приведя ее к удобному формату. Кажется после этого и сам алгоритм может стать попроще.
Подумай еще, как можно упростить твой алгоритм, так как сейчас очень много циклов в цикле

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +let days = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
У нас есть небольшое правило для использования const и let: если переменная не изменяется внутри функции, то мы используем const, если переменной необходимо изменить значение, то используем let. Удобное правило, можешь воспользоваться им, если захочешь

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +    currentHours = currentHours < 10 ? '0' + currentHours : String(currentHours);
```
`0{currentHours}`.slice(-2)
```

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +    }
Два условных выражения можно переписать на одно, подумай как можно это сделать

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +exports.convertTime = convertTime;
Зачем?

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> + * Переводит дату в количество секунд с начала недели
А зачем секунды?) Да еще и название функции при этом `toMinutes`

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +    let index2 = days.indexOf(time2.slice(0, 2));
Ты на протяжении работы всего алгоритма делаешь очень много слайсов с одной и той же целью. Почему бы тебе один раз не распарсить время, привести его к удобному для тебя формату и дальше пользоваться уже распарсенным временем?

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +    return index1 === index2 && toMinutes(time1) <= toMinutes(time2);
кажется `index1 < index2` и `index1 === index2 && toMinutes(time1) <= toMinutes(time2)` можно схлопнуть в одно выражение

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +        listOfTimes.push(schedule[guy].map(el => {
Название переменной должно говорить о том, что в ней находится. Непонятно, что лежит в переменной `el`

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +function addHalfHour(time) {
Вот здесь опять же. Сделаешь удобный для тебя формат времени и тебе станет в разы проще проводить операции со временем. Добавление 30 минут ко времени это же простая операция, а у тебя она очень сложная вышла

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +        for (let i = 0; i < goodTime.length; i++) {
Используешь for и при этом внутри цикла меняешь значение переменной i. Для for не очень практика, он подразумевает стабильный шаг. Кажется лучше использовать while в этом случае

2017-10-24 09:08 UTC, Mokoshka commented on robbery.js
> +function add(element, array, position) {
Функция `add` которая может взять и удалить из массива элемент. Что?

2017-10-24 09:46 UTC, San4eyZ commented
Перепишу-ка все с нуля наверное))

2017-10-26 05:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-26 05:12 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-26 08:50 UTC, Mokoshka requested changes

2017-10-26 08:50 UTC, Mokoshka commented on robbery.js
> +    }
Зачем так сложно?) Можно же просто поделить и взять целое число, разве нет?

2017-10-26 08:50 UTC, Mokoshka commented on robbery.js
> +        listOfTimes.push(schedule[guy].map(time => {
```
.map(time => ({ from: convertTime(time.from, bankZone), to: convertTime(time.to, bankZone) }))
```

2017-10-26 08:50 UTC, Mokoshka commented on robbery.js
> +    let appropriateTime = goodTime.filter(time => {
`.filter(time => time.to - time.from >= duration)`

2017-10-26 08:50 UTC, Mokoshka commented on robbery.js
> +    }).sort((obj1, obj2) => {
Здесь аналогично можно

2017-10-26 08:50 UTC, Mokoshka commented on robbery.js
> +            return template.replace('%HH', time.from.slice(3, 5))
Сначала ты формируешь строку, а потом снова ее парсишь. Не проще вернуть из функции toDate объект с часами, минутами и днем?

2017-10-26 09:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-26 09:09 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-26 09:27 UTC, Mokoshka requested changes

2017-10-26 09:27 UTC, Mokoshka commented on robbery.js
> +    return [days[day], newHours, newMinutes];
Ну вот не понятно что первый элемент массива это день, второй - часы и т.д.
Вот придется месяц добавить или неделю, и как быть?)
Удобно будет возвращать объект с полями `{ day, hour, minutes}`. Сюда будет легко добавить новые данные о времени

2017-10-26 09:27 UTC, Mokoshka commented on robbery.js
> +            time = toDate(time.from);
`[day, hours, minutes] = toDate(time.from)`

2017-10-26 09:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-26 09:41 UTC, Mokoshka approved these changes

2017-10-26 09:41 UTC, closed without merging