Носов Андрей
urfu-2017/javascript-task-3 pull request #49
Opened 2017-10-18 18:34 UTC by nosovandrew

2017-10-18 18:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 18:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 16

2017-10-18 18:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 18:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 16

2017-10-18 18:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 16

2017-10-18 19:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2017-10-18 19:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2017-10-18 19:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2017-10-18 19:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 19:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2017-10-18 19:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2017-10-18 20:15 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-18 20:16 UTC, nosovandrew commented
Приведу код в приятный внешний вид завтра(19.10), так что следующий коммит будет нужным

2017-10-19 07:40 UTC, maxvipon requested changes
Решение очень сложное, это оверинжениринг. Попробуй упростить.

Хардкод нужно убрать, сделать решение для любого набора входных данных.

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +    }
Что насчет остальных дней недели?

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +    if (goodTime >= 1440 && goodTime < 2880) {
Это называется магические цифры. Плохая практика.
Вместо цифр нужно использовать константы:
```js
const MIN = 60 * 1000;
const HOUR = 60 * MIN;
```

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +        let timeFrom = (bankTime[0].from + 1440 * day);
👆

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +    const regExp = /(\d+):(\d+)[+-](\d+)/;
оффсета может не быть, он может быть получасовой или четвертьчасовой

![image](https://user-images.githubusercontent.com/871596/31759169-ed82212a-b4c9-11e7-83f8-f362e11142bf.png)

[Полная картинка](https://upload.wikimedia.org/wikipedia/commons/e/e8/Standard_World_Time_Zones.png)

[wiki/Часовой_пояс](https://ru.wikipedia.org/wiki/Часовой_пояс)

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +    let gmt = workingHours.from.split('+')[1];
👆

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +    if (robberTo > 4320) {
👆

2017-10-19 07:40 UTC, maxvipon commented on robbery.js
> +    for (let day = 0; day < 3; day++) {
❌ Хардкод! Сломается на отличных от примера входных данных

2017-10-19 17:24 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-19 18:08 UTC, maxvipon commented
👌

2017-10-19 18:08 UTC, closed without merging