Update robbery.js
urfu-2017/javascript-task-3 pull request #60
Opened 2017-10-18 22:09 UTC by gus1234

Сразу хочу сказать , что я понимаю, что лучше было использовать Date, я бы просто не успел переписать.
Извиняюсь за архитектуру и непонятность , время поджимало.

2017-10-18 22:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-18 22:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-18 22:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-18 22:27 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-19 11:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-19 11:05 UTC, honest-hrundel commented
@gogoleff обрати внимание: решено доп. задание

2017-10-19 12:00 UTC, gus1234 commented
добавил проверку на существование подходящего времени при попытке найти попозже.

2017-10-26 12:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-26 12:08 UTC, honest-hrundel commented
@gogoleff обрати внимание: решено доп. задание

2017-11-26 08:45 UTC, f0rmat1k requested changes
Алгоритм получился крайне запутанный. Особенно много больших функций работы с временем, которые трудно читать. Что-то явно пошло не так с самого начала. Я могу принять это решение только как наполовину сделанное и только если ты исправишь описанные замечания.
 
Если есть время и желание, я б советовал пересмотреть решение.
Во-первых, стоит выбрать какую-то одну единицу измерения времени, с которой будешь работать. Например, минуты.
Далее. Есть график занятости друзей и работы банка.
![](https://cloud.githubusercontent.com/assets/4534405/19563495/a0ec90be-96f9-11e6-978e-826bcae3628b.png)  
Можно построить временные промежутки, скажем, в минутах с точкой отсчета от понедельника, когда каждый из них становится занят и становится свободен. Банк тоже можно по сути посчитать четвертым другом, который свободен весь раб. день. И потом эти промежутки можно отсортировать и найти подходящие моменты. Если совсем не будет идей, как сделать проще, можешь попробовать заглянуть в соседние решения.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +        if (invalidDays.indexOf(begin.split(' ')[0]) !== -1) {
Стоит исп-ть `includes`.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +function createScheduleOfEmployment(intervals, invalideTime) {
Employment имете несколько иное значение. Тут скорее речь о Busyness.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +        if (result === true) {
Тут можно было б чуть-чуть меньше дублирования сделать:
```js
if (result === false) {
   continue;
}

time[day].splice(i, 1);

if (result === true) {
   time[day] = time[day].concat(result);
}

i--;
break;
```

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +var invalidDays = 'ЧТПТСБВС';
Это стоит получить из `days`, чтоб не дублировать строковые данные.
Еще, странный выбор формата записи. Почему не массив, как `days`?

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +    let time = {};
Плохое, слишком общее название переменной.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +    invalideTime['ПН'] = [];
1. На первый взгляд кажется, что такой подход не очень хороший, т.к. если, например, изменятся возможные для ограбления дни, код придется менять больше, чем в одном месте. В крайнем случае стоило пройтись циклом по invalidDays и в нем записать там эти пустые массивы.
2. Даже если такой код необходим, почему бы сразу не сделать:
```js
let invalideTime = {
  'ПН': []
};
```
Но как я писал выше, надо циклом.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +        workWithShedule(schedule, name, timeZone, invalideTime);
1. Плохое название метода. Буквально переводится «работать с расписанием». Если конечной целью метода является заполнение неподходящего времени, стоит так и назвать `fillInvalidTime`.

2. Не очень хорошо, когда данные много меняются по ссылкам. Такой код тяжелее воспринимать. + их сложно тестировать. Лучше, чтоб методы что-то возвращали, например:
```js
let invalideTime = getInvalidTime(scheldue, name, timeZone, invalidDays);
```
Это замечание касается многих таких функций, например, `findingFreeTime`.

3. Алгоритм, основанный на поиске неподходящего времени не так эффективен, как поиск подходящего. решение получилось в 2-3 раза более громоздким, чем могло.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +    let timeZone = workingHours.from.slice(5);
Стоит назвать переменную `bankTimeZone`. У нас больше, чем 1 таймзона в задании. Удобно, когда сразу понятно, о какой именно идет речь, когда читаешь код.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +    time['СР'] = [{ from: 'СР ' + workingHours.from.slice(0, 5),
Этот код явно повторяющийся, нужно оформлять как функцию.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +            i = correctingOfTime(invalideTime, day, time, i);
Тоже название неговорящее. Что за корректировка?

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +function differenceTimes(firstTime, secondTime) {
1. Плохое название функции "разность времен". Оно должно начинаться с глагола.
2. Какая-то совсем сложная конструкция if-else'ов. Тут явно что-то не так. И, честно говоря, смотря на это, не очень хочется вникать.

2017-11-26 08:45 UTC, f0rmat1k commented on robbery.js
> +    let Hours = parseInt(time.slice(3, 5)) + (parseInt(timeZone) - parseInt(time.slice(8)));
Зачем переменная с большой буквы?

2017-11-27 14:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-11-27 14:05 UTC, honest-hrundel commented
@f0rmat1k обрати внимание: решено доп. задание

2017-11-27 14:12 UTC, gus1234 commented
@f0rmat1k лектор говорил, что при выполнении этого таска не обязательно надо было работать с Date. С этим и связано большое количество функций работы со временем. Ну и , конечно, алгоритм можно было сделать проще , с этим я согласен.

2017-11-28 20:26 UTC, f0rmat1k requested changes

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +    let firstDay = firstTime.split(' ')[0];
Это неоптимальное сравнение. Почему бы не перевести firstTime и secondTime в единую плоскость. Например, легко понять, что (например), firstTime — это 1200 минут с начала понедельника, а secondTime — это 1300 минут. После этого можно их сравнить без всяких if'ов на дни\часы\минуты.

Также замечание, что много повторяющегося кода. Функция парсинга времени должна быть одна. Сейчас ты много где в коде пишешь одни и те же сплиты для извлечения дней, часов и т.д. Напиши просто функцию parseTime.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +        let result = calculatingTimeDifference(freeTime[day][i], wrongTime);
функции (которые тем более что-то возвращают) не должны начинаться с ing'ового глагола.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +function unionOfTimesPt2(firstTime, secondTime) {
Название функции не должно быть существительным. Что такое pt2?

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +function unionOfTimes(firstTime, secondTime) {
Название функции не должно быть существительным.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +function sepationToInterval(firstTime, secondTime) {
Название функции не должно быть существительным.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +function comprasionMinutes(validTime, duration, timeOfRobbery, flag) {
Название функции не должно быть существительным.
Почему в названии ф-ии речь идет о минутах, хотя она их не на вход не принимает не на выходе не возвращает?

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +    let find = false;
Очень нежелательно булевую переменную называть глаголом. Полагаю, тут должно было быть `found`?

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +function correctingFreeTime(invalideTime, day, freeTime, i) {
Название функции с ing. Если функция что-то возвращает, и это не булевое значение, почти всегда стоит начинать название с `get`. Этот маркер позволяет понять, что функция что-то возвращает, а не меняет где-то.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +function findingFreeTime(invalideTime, freeTime) {
ing

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +            freeTime[day] = freeTime[day].concat(result);
плохо когда функция и что-то возвращает и что-то внутри себя меняет по ссылке.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +            i = correctingFreeTime(invalideTime, day, obj, i);
i = корректировкаСвободногоВремени. В i принято записывать всякие индекса. Если он там, почему функция корректировки времени возвращает какой-то индекс? Кране трудно такой код читать и понимать.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +    let obj = Object.assign(invalideTime);
В чем смысл этой строки? Если ты хотел создать копию объекта, то стоило добавить `{},` перед `invalidTime`. Сейчас этот код эквивалентент `let obj = invalideTime`. Есть еще такие же места в коде выше.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +                    .indexOf(element), 1, result);
Вот этот перенос никакой проблемы не решает, но читаемость сильно ухудшает. Если он все же нужен, стоит последнюю скобку переносить на новую строку, чтоб понять, что она относится к .splice(.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +        if (begin.split(' ')[0] !== end.split(' ')[0]) {
Вот тут должно быть что-то понятное написано быть. Повторяющиеся вещи типа .split(' ')[0] стоит оформить в функции, а их результат в понятные для восприятия кода переменные:
```js
var startDayOfWeek = getDay(startDayOfWeek);

function getDay(time){
  return time.split(' ')[0]
}
```

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +        let begin = normalizeTime(times.from, bankTimeZone);
begin — это глагол. Не стоит так называть переменные для строк.

2017-11-28 20:26 UTC, f0rmat1k commented on robbery.js
> +        to: day + ' ' + workingHours.to.slice(0, 5) }];
.slice(0, 5) — это повторяющийся код, стоит оформить в функцию.

2017-12-06 17:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-12-06 17:59 UTC, honest-hrundel commented
@f0rmat1k обрати внимание: решено доп. задание

2017-12-06 18:04 UTC, gus1234 commented
@f0rmat1k переписал все, согласно твоему совету.
"Можно построить временные промежутки, скажем, в минутах с точкой отсчета от понедельника, когда каждый из них становится занят и становится свободен. Банк тоже можно по сути посчитать четвертым другом, который свободен весь раб. день. И потом эти промежутки можно отсортировать и найти подходящие моменты. "

2017-12-07 21:44 UTC, f0rmat1k approved these changes

2017-12-07 21:44 UTC, closed without merging

2017-12-07 21:45 UTC, f0rmat1k commented
За старания и из-за задержки проверок приму, как полное.