Леонид Мелкозёров
urfu-2017/javascript-task-3 pull request #64
Opened 2017-10-19 06:30 UTC by danmerus

2017-10-19 06:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 06:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 07:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 07:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 07:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-19 18:55 UTC, sameoldmadness commented on robbery.js
> +function formDict(name) {
Насколько я могу судить из дальнейшего кода, эта функция в таком виде не нужна.

Достаточно вызывать `toMinsFromMonday` напрямую из `getFreeTimeIntervals`.

2017-10-19 19:22 UTC, sameoldmadness requested changes

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +function helper1(t1, t2, t3, t4) {
Если эта функция нужна только для того, чтобы пройти проверку `eslint`, я бы предложил отключить проверку.

Выглядеть это будет как-то так:

```js
function findIntersection(inter1, inter2) { // eslint-disable-line max-statements
```

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +    if ((t2 <= t3) || (t1 >= t4)) {
Кажется, тут со специфичностью тоже всё в порядке и скобки не нужны.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +function trickSystem(period, arr) {
Название, мягко говоря, странное. Почему так?

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +        out.push(findIntersection(arr[i], period));
Разве нужно добавлять пустые интервалы?

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +    res += (parseInt(hours) - parseInt(zone)) * 60 + parseInt(mins);
`parseInt`  вторым _обязательным_ аргументом принимает основание системы счисления.

Может внезапно взорваться, когда какой-нибудь старый браузер распарсит `'09'` как 0 в восьмеричной.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +    switch (day) {
Обычно компактнее получается использовать объекты в место `switch`, но это на твоё усмотрение.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +    var Op = (parseInt(hOpens) - zone) * 60 + parseInt(mOpens);
Задачка объёмная, поэтому я не буду просить поменять имена переменных на более осмысленные. Но, в целом, будь готов.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +    for (var i = 0; i < intervals.length; i++) {
Также на будущее – привыкай к `let`, оператору РАЗРУШЕНИЯ и `map`/`filter`/`reduce` – код будет выглядеть аккуратнее.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +    out.push([Op, Clo], [Op + 1440, Clo + 1440], [Op + 2880, Clo + 2880]);
Если 60 можно оставить в коде, то 1440 и 2880 надо бы уже вынести в константы с понятными именами.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +            return exists;
Тут можно без промежуточных переменных обойтись.

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +            var m = parsedStart[1].split(':')[1];
Может, данные сразу хранить в таком варианте, чтобы не приходилось их извлекать повторно?

2017-10-19 19:22 UTC, sameoldmadness commented on robbery.js
> +            if (getRightTime(schedule, duration, workingHours) === -1) {
Можно использовать метод: `if (!this.exists())`.

2017-10-20 07:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-20 07:47 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-25 20:32 UTC, sameoldmadness approved these changes

2017-10-25 20:32 UTC, closed without merging