done
urfu-2017/javascript-task-3 pull request #65
Opened 2017-10-19 07:07 UTC by HEXBATAET

2017-10-19 07:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 16

2017-10-19 07:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 16

2017-10-19 07:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 16

2017-10-19 07:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 16

2017-10-19 08:04 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-19 13:50 UTC, eugenest requested changes
в целом ок
исправляй и перезасылай

в телеграмме я tim_evg

2017-10-19 13:50 UTC, eugenest commented on .vscode/launch.json
> +{
можно не исправлять, но вещи, не относящиеся к задаче, должны быть в гитигноре

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +    daysForRob.forEach(function (day) {
.map больше подходит

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +    let dateTime = new Date(2017, 10, day, hours, minutes);
почему 2017/10?

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +
пустая строка не нужна

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +    let performedSchedule = [schedule[0]];
рекомендация: блок объявления переменных лучше отделять от остального кода, так легче читать

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +        performedSchedule.forEach(function (perfomInter) {
здесь лучше подходит Array.some()

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +    for (let i = 0; i <= schedule.length - 2; i++) {
что за 2? лучше вынести в константу

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +    );
надо вернуть на строчку назад

2017-10-19 13:50 UTC, eugenest commented on robbery.js
> +                hours = '0'.concat(String(hours));
не важно, '0' + 1 или '0' + '1', всё равно будет '01'
вместо конката можно просто +

2017-10-19 13:50 UTC, eugenest commented
🍅

2017-10-21 08:51 UTC, HEXBATAET commented on robbery.js
> +    let dateTime = new Date(2017, 10, day, hours, minutes);
На самом деле можно почти любую дату взять. Для задачи нужно всего лишь уметь сравнивать и вычитать интервалы, Date с этим справляется на ура, но приходится соблюдать все требования.

2017-10-21 09:35 UTC, HEXBATAET commented on robbery.js
> +        performedSchedule.forEach(function (perfomInter) {
Мне нужно запомнить интервал, который пересекается. К месту использовать в Array.some() замыкание?

2017-10-21 09:37 UTC, HEXBATAET commented on robbery.js
> +    for (let i = 0; i <= schedule.length - 2; i++) {
Это всё равно что (let i = 0; i < schedule.length - 1; i++) Ограничение индекса, чтобы не выйти за границы массива т.к. беру по два элементы из массива

2017-10-21 09:40 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-21 09:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-22 14:45 UTC, eugenest reviewed
1 фикс

2017-10-22 14:45 UTC, eugenest commented on robbery.js
> +        if (performedSchedule.some(function (perfomInter) {
выноси кондишн в переменную, так проще читать

в остальном норм
заливай и окаю

2017-10-23 12:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-23 14:32 UTC, eugenest approved these changes

2017-10-23 14:32 UTC, closed without merging