task done
urfu-2017/javascript-task-3 pull request #72
Opened 2017-10-19 12:01 UTC by RomanDengin

2017-10-19 12:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 16

2017-10-19 12:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-19 12:19 UTC, honest-hrundel commented
@Grimfrid обрати внимание: решено доп. задание

2017-10-23 07:45 UTC, Grimfrid commented on robbery.js
> +function getDayNumber(day) {
как на счет того чтобы запихнуть названия в массив и работать с индексами? Пиши расскажу как, если интересно

2017-10-23 18:39 UTC, Grimfrid commented on robbery.js
> +    var day = getDayNameByNumber(Math.floor(minutes / 1440));
`1440` похоже на константу, давай все константы вынесем в `const` с понятным именем , это сделает код легче для восприятия

2017-10-23 18:53 UTC, Grimfrid commented on robbery.js
> +function findInterSections(dannyTimes, rustyTimes, linusTimes, bankTimes) {
Вот тут одно из самых слабых мест (5 пересечений), попробуй искать пересечения вот так:
((банк X человек#1) X человек#2) X человек#3) и конечно же не привязываться к кол-ву и именам

2017-10-23 18:55 UTC, Grimfrid commented on robbery.js
>          tryLater: function () {
`return false` - это не решение доп. задания =)

2017-10-23 18:59 UTC, Grimfrid requested changes
Из общего обязательного:
1) Представь что тебе нужно посчитать все это не для троих человек, а для четверых, сколько изменений придется внести в код? Ответ на этот вопрос покажет тебе все слабые места кода. Давай попробуем не привязываться к именам и кол-ву людей. 

Из общего необязательного:
1) По желанию можешь добавить к функциям JSDoc, будет легче разобрать код

Будут вопросы пиши в слак

🍅

2017-10-25 20:39 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-25 20:39 UTC, honest-hrundel commented
@Grimfrid обрати внимание: решено доп. задание

2017-10-25 20:44 UTC, RomanDengin commented
🍏 
* Написал решение общее (теперь нет привязок к количеству людей и именам)
* Документацию добавил
* Звёздочка сделана

2017-10-29 13:01 UTC, Grimfrid commented
сейчас тесты на доп задание не запускаются (неправильно экспортируется переменная `isStar`), если ты ее правильно экспортнешь, то тесты упадут. Если хочешь звездочку, надо починить

2017-10-29 16:02 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-29 16:02 UTC, honest-hrundel commented
@Grimfrid обрати внимание: решено доп. задание

2017-10-29 16:04 UTC, RomanDengin commented
🍏 
импорт исправил
star тоже

2017-10-31 20:36 UTC, Grimfrid commented on robbery.js
> +/* module.exports = {
На будущее, закомментированный код лучше не коммитить

2017-10-31 20:37 UTC, Grimfrid reviewed
ок

2017-10-31 20:37 UTC, closed without merging