better late than never
urfu-2017/javascript-task-3 pull request #75
Opened 2017-10-21 20:31 UTC by iriskis

2017-10-21 20:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-10-22 11:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-22 11:09 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-24 10:07 UTC, Mokoshka requested changes
Стоит поменять формат времени, код должен от этого упроститься

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +            return start !== undefined;
`return Boolean(start)`?

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +            if (start === undefined) {
`if (!start)`?

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +    let datePointes = findDatePointes(schedule, workingHours);
У нас есть небольшое правило для использования const и let: если переменная не изменяется внутри функции, то мы используем const, если переменной необходимо изменить значение, то используем let. Удобное правило, можешь воспользоваться им, если захочешь

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +    ROBBERS.forEach(robber => {
Указав имена всех грабителей, ты лишила свой алгоритм универсальности. Можно не завязываться на их имена.

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +            let [dayFrom, hoursFrom, minutesFrom] = parseTime(date.from, timeZoneforBank);
Парсишь время это ок. Но ты возвращаешь время в трех единицах, а потом при работе с ними приходится указывать несколько if, например для сравнения.
Кажется, будет лучше, например, хранить время в единой единице измерения, например в минутах. Так и сравнивать будет намного легче

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +    };
Запись можно сделать аккуратнее, используя возможности es6: `return { day, hours, minutes, type }`

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +    let minutesTo = Number(dateTo[2]);
Это очень похоже на parseTime. Может стоит сделать эту функцию универсальнее?

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +            minutes = 0;
Почему 0:0? Почему не 23:59?

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +    datePointes.sort((a, b) => compareDate(a, b));
`datePointes.sort(compareDate)`

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +        }
```
let counter = datePointes[i].type === 'end' ? 1 : -1;
busy = busy + counter;
```

Только название для counter подбери более подходящее

2017-10-24 10:07 UTC, Mokoshka commented on robbery.js
> +        if (busy === 0 && moreThanDuration(datePointes[i], datePointes[i + 1], duration)) {
`!busy && ...`

2017-10-24 12:05 UTC, iriskis commented on robbery.js
> +            minutes = 0;
копипаста неудачная:D

2017-10-25 23:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-10-25 23:58 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-10-26 06:13 UTC, Mokoshka requested changes
Поправишь замечания и закрою задачу

2017-10-26 06:13 UTC, Mokoshka commented on robbery.js
> +                .replace('%HH', ('0' + start.hours).slice(-2))
`0{start.hours}`

2017-10-26 06:13 UTC, Mokoshka commented on robbery.js
> +    for (let robber of Object.keys(shedule)) {
Здесь можно использовать `for (let robber in shedule)` или `Object.keys(shedule).forEach()`

2017-10-26 06:13 UTC, Mokoshka commented on robbery.js
> +    for (let i = 0; i < 3; i++) {
Предлагаю циклы писать в едином стиле. Либо `for ... in/of ...` либо `[].forEach/map/reduce`.
Здесь делать for с счетчиком нет смысла. Я бы посоветовала использовать метод reduce, так как здесь явно есть аккумулирующий объект, в который ты пушишь каждую итерацию

2017-10-26 06:13 UTC, Mokoshka commented on robbery.js
> +        datePointes.push(getDatePoint(workingTo, 'end'));
`datePointes.push(getDatePoint(...), getDatePoint(...))`

2017-10-26 06:13 UTC, Mokoshka commented on robbery.js
> +        , []);
Ад перфекциониста) Лучше так `}, []);`.

2017-10-26 09:34 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-11-03 16:02 UTC, Mokoshka approved these changes

2017-11-03 16:02 UTC, closed without merging