мне там баллов немного не хватает
urfu-2017/javascript-task-3 pull request #78
Opened 2017-12-15 17:21 UTC by AlexBarett

2017-12-15 17:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2017-12-15 17:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2017-12-15 17:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-12-15 17:42 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-12-18 06:55 UTC, eugenest requested changes

2017-12-18 06:55 UTC, eugenest commented on robbery.js
> +    schedule.Danny.forEach(filterTimeSegment);
код не должен зависеть от данных, а ты обращаешься к каждому отдельному грабителю

2017-12-18 06:55 UTC, eugenest commented on robbery.js
> +const halfWeek = {
странное название для странного содержимого

2017-12-18 06:55 UTC, eugenest commented on robbery.js
> +    let openMonday = toMinutes('ПН ' + workingHours.from, 0);
снова отталкиваешься от данных

если они чуть-чуть поменяются, тебе придётся переписывать код
так быть не должно

2017-12-18 06:55 UTC, eugenest commented on robbery.js
> +function combimeMinutes(availableMinutes) {
combine?

2017-12-18 07:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 08:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 08:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 08:31 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-12-18 08:31 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-12-18 08:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 08:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 09:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 09:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 10:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2017-12-18 10:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-12-18 10:08 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-12-18 11:33 UTC, closed without merging