Никонов Андрей
urfu-2017/javascript-task-3 pull request #9
Opened 2017-10-14 09:28 UTC by andrejNik

2017-10-14 09:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2017-10-14 10:38 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2017-10-19 20:14 UTC, Grimfrid requested changes
Сам алгоритм хорош, поправь замечания и норм. А почему `isStart = false`?

🍅

2017-10-19 20:14 UTC, Grimfrid commented on segmentHelper.js
> +    let first;
тут можно упростить функцию, засунуть сегменты в массив и отсортировать

2017-10-19 20:14 UTC, Grimfrid commented on segmentHelper.js
> + *@param {Object} segment1 - объекта вида {start:number, end: number, timezone:number}
посмотри на `@typedef` в JSDoc, тогда не надо будет в описании параметра описывать его поля или делается вот так
```
@param {Object} segment1 - объект с интервалом времени
@param {Number} segment1.start - начало интервала
...
```
но лучше все таки `@typedef`

2017-10-19 20:14 UTC, Grimfrid commented on segmentHelper.js
> +
нужен JSDoc

2017-10-19 20:14 UTC, Grimfrid commented on segmentHelper.js
> + *@param {Object} segment1 - объекта вида {start:number, end: number, timezone:number}
это касается всех остальных подобных мест, не буду писать это везде

2017-10-19 20:14 UTC, Grimfrid commented on segmentHelper.js
> +
JSDoc

2017-10-19 20:14 UTC, Grimfrid commented on robbery.js
> +        duration: duration,
А зачем это в возвращаемом объекте?

2017-10-19 20:14 UTC, Grimfrid commented on segmentHelper.js
> +        let startingMonent = getStartingMoment(workingSegment, start);
Опечатка: startingMo`n`ent

2017-11-04 10:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2017-11-04 10:14 UTC, honest-hrundel commented
@Grimfrid обрати внимание: решено доп. задание

2017-11-07 16:35 UTC, closed without merging